### ISSUE TITLE
Help w/ Making this work

### ISSUE THREAD

**Issue by tonedwtf** [inlife/discord-global-mutual#4]
I don't understand what npm install means, I installed node and everything and I tried to use npm install into the directory and all it said was,
```
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\david\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\david\package.json'
npm WARN david No description
npm WARN david No repository field.
npm WARN david No README data
npm WARN david No license field.

+ discord-global-mutual@1.0.0
updated 1 package and audited 16 packages in 0.647s
found 0 vulnerabilities
```

**Comment by inlife** [comment]
Please follow the installation instructions: https://github.com/inlife/discord-global-mutual#installation

**Comment by tonedwtf** [comment]
Yes I tried my best to, and I don't know what I'm doing, I typed into cmd prompt,
`npm install C:\Users\david\Desktop\discord-global-mutual-master`
which then gives me an output of,
```
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\david\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\david\package.json'
npm WARN david No description
npm WARN david No repository field.
npm WARN david No README data
npm WARN david No license field.

+ discord-global-mutual@1.0.0
updated 1 package and audited 16 packages in 0.742s
found 0 vulnerabilities
```
The folder looks like this,
![image](https://user-images.githubusercontent.com/34613124/64131910-6af67700-cd91-11e9-9a22-6a1a87e52d54.png)

**Comment by inlife** [comment]
I updated the readme instructions, hope that would be more clear:
https://github.com/inlife/discord-global-mutual/blob/master/README.md#installation

**Comment by tonedwtf** [comment]
Ok thanks, I'll see if it works.

edit: It work's thank's so much!

**Comment by inlife** [comment]
cheers!
