### ISSUE TITLE
requesting users for guild never stops

### ISSUE THREAD

**Issue by SimplisticGH** [inlife/discord-global-mutual#7]
it just keeps saying the same thing over and over
![image](https://user-images.githubusercontent.com/43940438/69890302-8a327100-12ba-11ea-813d-f7068415fe8f.png)

**Comment by inlife** [comment]
Hello @SimplisticGH 

That is the intended behavior. Since a guild has a lot of members, and discord API limits how many users can be fetched per single request, it sequentially "asks" the guild about the next batch over and over until there are no more users.

**Comment by SimplisticGH** [comment]
Ah ok
